import type { ImageSourcePropType } from 'react-native';

// Generated by scripts/generate-call-pattern-stickers.cjs: small transparent copies of the chat stickers for the
// call wallpaper. Re-run that script after changing stickers; do not edit by hand.
export const PATTERN_STICKERS: ImageSourcePropType[] = [
  require('./pattern/emotions-heart-eyes.png'),
  require('./pattern/emotions-huggie.png'),
  require('./pattern/emotions-relaxed.png'),
  require('./pattern/emotions-stop.png'),
  require('./pattern/emotions-teasing.png'),
  require('./pattern/funny-bozo.png'),
  require('./pattern/funny-music.png'),
  require('./pattern/funny-w-e2.png'),
  require('./pattern/funny-we1.png'),
  require('./pattern/greetings-cheers.png'),
  require('./pattern/greetings-good-job.png'),
  require('./pattern/greetings-hello.png'),
  require('./pattern/greetings-thank-you.png'),
  require('./pattern/greetings-you-re-welcome.png'),
  require('./pattern/reactions-annoyed.png'),
  require('./pattern/reactions-confused.png'),
  require('./pattern/reactions-dancing.png'),
  require('./pattern/reactions-derp.png'),
  require('./pattern/reactions-laughing.png'),
  require('./pattern/reactions-pleading.png'),
  require('./pattern/reactions-sleepy.png'),
  require('./pattern/reactions-smug.png'),
  require('./pattern/reactions-surprised.png'),
  require('./pattern/reactions-worried.png'),
  require('./pattern/thinking-detective.png'),
  require('./pattern/thinking-taking-notes.png'),
  require('./pattern/thinking-thinking.png'),
];
