import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Image } from 'expo-image';
import { CalendarDays, MapPin, Plus, Search, Users } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import PageHeader from '@/components/ui/PageHeader';
import CreateEventModal from '@/components/events/createEventModal/CreateEventModal';
import { eventService, type EventAttendanceStatus } from '@/lib/services/EventService';
import { useAppTheme } from '@/lib/contexts/ThemeContext';
import type { Event } from '@/types/eventTypes';
import { linkPresentationService } from '@/lib/services/LinkPresentationService';

export default function EventsPage() {
  const router = useRouter(); const { colors } = useAppTheme(); const styles = useMemo(() => createStyles(colors), [colors]);
  const [events, setEvents] = useState<Event[]>([]); const [attendance, setAttendance] = useState<{ [eventId: string]: EventAttendanceStatus }>({}); const [search, setSearch] = useState(''); const [category, setCategory] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(''); const [createOpen, setCreateOpen] = useState(false); const [workingEventId, setWorkingEventId] = useState<string | null>(null);
  const load = useCallback(async () => { setError(''); try { const liveEvents = await eventService.fetchEvents(); setEvents(liveEvents); const attendanceEntries = await Promise.all(liveEvents.slice(0, 40).flatMap((event): Promise<[string, EventAttendanceStatus]>[] => event.id ? [eventService.getAttendance(event.id).then((state) => [event.id as string, state])] : [])); setAttendance(Object.fromEntries(attendanceEntries)); } catch (loadError: unknown) { setError(loadError instanceof Error ? loadError.message : 'Events could not be loaded.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const categories = useMemo(() => [...new Set(events.map((event) => event.category).filter((value): value is string => Boolean(value)))].sort(), [events]);
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return events.filter((event) => (!category || event.category === category) && (!query || [event.title, event.summary, event.location, event.category ?? ''].some((value) => value.toLowerCase().includes(query)))); }, [category, events, search]);
  const handleAttendance = async (eventId: string) => { setWorkingEventId(eventId); setError(''); try { const state = await eventService.toggleAttendance(eventId); setAttendance((current) => ({ ...current, [eventId]: state })); } catch (attendanceError: unknown) { setError(attendanceError instanceof Error ? attendanceError.message : 'Attendance could not be updated.'); } finally { setWorkingEventId(null); } };
  return <SafeAreaView edges={['top', 'left', 'right']} style={styles.safeArea}><PageHeader title="Events" onBackPress={() => router.back()} /><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} tintColor="#10b981" />}>
    <View style={styles.hero}><CalendarDays size={30} color="#052e16" /><View style={styles.heroCopy}><Text style={styles.heroTitle}>Discover live events</Text><Text style={styles.heroText}>{events.length} upcoming community and public events</Text></View><TouchableOpacity onPress={() => setCreateOpen(true)} style={styles.addButton}><Plus size={21} color="#ffffff" /></TouchableOpacity></View>
    <View style={styles.searchBox}><Search size={19} color={colors.mutedText} /><TextInput value={search} onChangeText={setSearch} placeholder="Search events…" placeholderTextColor={colors.mutedText} style={styles.searchInput} /></View>
    {categories.length ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}><TouchableOpacity onPress={() => setCategory(null)} style={[styles.chip, !category && styles.chipActive]}><Text style={[styles.chipText, !category && styles.chipTextActive]}>All</Text></TouchableOpacity>{categories.map((item) => <TouchableOpacity key={item} onPress={() => setCategory(item)} style={[styles.chip, category === item && styles.chipActive]}><Text style={[styles.chipText, category === item && styles.chipTextActive]}>{item}</Text></TouchableOpacity>)}</ScrollView> : null}
    {error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}{loading ? <ActivityIndicator size="large" color="#10b981" style={styles.loader} /> : filtered.length === 0 ? <View style={styles.empty}><CalendarDays size={40} color={colors.mutedText} /><Text style={styles.eventTitle}>No events found</Text><Text style={styles.muted}>Create an event or adjust your search.</Text></View> : filtered.map((event) => { const eventId = event.id; const state = eventId ? attendance[eventId] : undefined; const locationPresentation = linkPresentationService.presentLocation(event.location); const locationLabel = locationPresentation.detail ? `${locationPresentation.title} · ${locationPresentation.detail}` : locationPresentation.title; return <View key={eventId ?? event.title} style={styles.card}>{event.image ? <Image source={{ uri: event.image }} recyclingKey={`event-${eventId}-${event.image}`} contentFit="cover" style={styles.image} /> : <View style={styles.imagePlaceholder}><CalendarDays size={34} color="#10b981" /></View>}<View style={styles.cardBody}><View style={styles.cardHeader}><Text style={styles.eventTitle}>{event.title}</Text>{event.category ? <Text style={styles.category}>{event.category}</Text> : null}</View><Text numberOfLines={3} style={styles.summary}>{event.summary}</Text><View style={styles.meta}><CalendarDays size={15} color="#10b981" /><Text style={styles.muted}>{new Date(event.startDate).toLocaleString()}</Text></View><View style={styles.meta}><MapPin size={15} color="#10b981" /><Text numberOfLines={1} ellipsizeMode="tail" style={[styles.muted, styles.locationText]}>{locationLabel}</Text></View>{eventId ? <TouchableOpacity disabled={workingEventId === eventId} onPress={() => void handleAttendance(eventId)} style={[styles.attendButton, state?.isAttending && styles.attendingButton]}><Users size={17} color={state?.isAttending ? '#047857' : '#ffffff'} /><Text style={[styles.attendText, state?.isAttending && styles.attendingText]}>{state?.isAttending ? 'Going' : 'Attend'} · {state?.attendeeCount ?? 0}</Text></TouchableOpacity> : null}</View></View>; })}
  </ScrollView><CreateEventModal visible={createOpen} onClose={() => setCreateOpen(false)} onCreated={() => { setCreateOpen(false); void load(); }} /></SafeAreaView>;
}

type ThemeColors = ReturnType<typeof useAppTheme>['colors'];
const createStyles = (colors: ThemeColors) => StyleSheet.create({ safeArea: { flex: 1, backgroundColor: colors.canvas }, content: { padding: 18, paddingBottom: 48, gap: 14 }, hero: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#34d399', borderRadius: 20, padding: 17 }, heroCopy: { flex: 1 }, heroTitle: { color: '#052e16', fontSize: 20, fontWeight: '900' }, heroText: { color: '#065f46', fontSize: 12, marginTop: 3 }, addButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#047857', alignItems: 'center', justifyContent: 'center' }, searchBox: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 14, paddingHorizontal: 13 }, searchInput: { flex: 1, color: colors.text, paddingVertical: 12 }, chips: { gap: 8 }, chip: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 18, paddingHorizontal: 12, paddingVertical: 7 }, chipActive: { backgroundColor: '#10b981', borderColor: '#10b981' }, chipText: { color: colors.mutedText, fontWeight: '700', fontSize: 12 }, chipTextActive: { color: '#ffffff' }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 18, overflow: 'hidden' }, image: { width: '100%', height: 185 }, imagePlaceholder: { width: '100%', height: 125, backgroundColor: colors.control, alignItems: 'center', justifyContent: 'center' }, cardBody: { padding: 15, gap: 8 }, cardHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 }, eventTitle: { flex: 1, color: colors.text, fontSize: 17, fontWeight: '900' }, category: { color: colors.successText, backgroundColor: colors.successSurface, borderRadius: 12, paddingHorizontal: 8, paddingVertical: 4, fontSize: 10, fontWeight: '800' }, summary: { color: colors.secondaryText, lineHeight: 20 }, meta: { flexDirection: 'row', alignItems: 'center', gap: 6 }, muted: { color: colors.mutedText, fontSize: 12 }, locationText: { flex: 1 }, attendButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, minHeight: 43, borderRadius: 12, backgroundColor: '#10b981', marginTop: 4 }, attendingButton: { backgroundColor: colors.successSurface }, attendText: { color: '#ffffff', fontWeight: '900' }, attendingText: { color: colors.successText }, error: { color: colors.destructiveText, backgroundColor: colors.destructiveSurface, borderRadius: 10, padding: 10 }, loader: { marginVertical: 50 }, empty: { alignItems: 'center', gap: 8, paddingVertical: 50 } });
