import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Text, TextInput, TouchableOpacity, View } from 'react-native';
import Icon from 'react-native-vector-icons/Feather';
import CustomModal from '@/components/ui/CustomModal';
import { AdminModerationService, type AdminModerationReport } from '@/lib/services/AdminModerationService';

const moderationService = AdminModerationService.getInstance();

export default function ModerationSection() {
  const [reports, setReports] = useState<AdminModerationReport[]>([]);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { setReports(await moderationService.fetchReports()); } catch (error: unknown) { setMessage(error instanceof Error ? error.message : 'Reports could not be loaded'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => { const query = search.trim().toLowerCase(); return query ? reports.filter((report) => `${report.reason} ${report.contentType} ${report.reporterName} ${report.status}`.toLowerCase().includes(query)) : reports; }, [reports, search]);
  const handleAction = async (report: AdminModerationReport, action: 'dismiss' | 'resolved_no_violation') => { if (busyId) return; setBusyId(report.id); try { await moderationService.takeAction(report.id, action, action === 'dismiss' ? 'Report dismissed from mobile moderation workspace' : 'Reviewed with no violation found'); setReports((current) => current.map((item) => item.id === report.id ? { ...item, status: action === 'dismiss' ? 'dismissed' : 'resolved' } : item)); setMessage(action === 'dismiss' ? 'Report dismissed.' : 'Report resolved with no violation.'); } catch (error: unknown) { setMessage(error instanceof Error ? error.message : 'Moderation action failed'); } finally { setBusyId(null); } };
  if (loading) return <View style={{ paddingVertical: 50, alignItems: 'center' }}><ActivityIndicator color="#10b981" /><Text style={{ marginTop: 8, color: '#64748b' }}>Loading reports…</Text></View>;
  return <><View style={{ flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, marginBottom: 14, borderRadius: 14, backgroundColor: '#f1f5f9' }}><Icon name="search" size={18} color="#64748b" /><TextInput value={search} onChangeText={setSearch} placeholder="Search reports" style={{ flex: 1, padding: 11, color: '#0f172a' }} /></View>{visible.length === 0 ? <View style={{ padding: 36, alignItems: 'center' }}><Icon name="check-circle" size={38} color="#10b981" /><Text style={{ marginTop: 10, fontWeight: '900', color: '#334155' }}>No reports found</Text></View> : visible.map((report) => <View key={report.id} style={{ padding: 15, marginBottom: 10, borderRadius: 16, backgroundColor: '#fff', borderWidth: 1, borderColor: report.severity === 'critical' || report.severity === 'high' ? '#fecaca' : '#e2e8f0' }}><View style={{ flexDirection: 'row' }}><Text style={{ flex: 1, color: '#0f172a', fontWeight: '900' }}>{report.reason}</Text><Text style={{ color: report.status === 'pending' ? '#b45309' : '#64748b', fontSize: 11, fontWeight: '800', textTransform: 'uppercase' }}>{report.status}</Text></View><Text style={{ marginTop: 5, color: '#64748b', fontSize: 12 }}>{report.contentType} · reported by {report.reporterName || 'Ourlime user'}</Text>{report.description ? <Text style={{ marginTop: 8, color: '#475569', lineHeight: 19 }}>{report.description}</Text> : null}{report.status === 'pending' || report.status === 'under_review' ? <View style={{ flexDirection: 'row', marginTop: 12 }}><TouchableOpacity disabled={busyId === report.id} onPress={() => void handleAction(report, 'resolved_no_violation')} style={{ flex: 1, alignItems: 'center', padding: 10, borderRadius: 12, backgroundColor: '#d1fae5' }}><Text style={{ color: '#047857', fontWeight: '800' }}>No violation</Text></TouchableOpacity><TouchableOpacity disabled={busyId === report.id} onPress={() => void handleAction(report, 'dismiss')} style={{ flex: 1, alignItems: 'center', padding: 10, marginLeft: 8, borderRadius: 12, backgroundColor: '#f1f5f9' }}><Text style={{ color: '#475569', fontWeight: '800' }}>Dismiss</Text></TouchableOpacity></View> : null}</View>)}<CustomModal visible={Boolean(message)} title="Content moderation" message={message ?? ''} type="info" onClose={() => setMessage(null)} /></>;
}
