import { useMemo, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AlertTriangle, Check, X } from 'lucide-react-native';
import { useAppTheme } from '@/lib/contexts/ThemeContext';
import AnimatedActionButton from '@/components/ui/AnimatedActionButton';
import { ModalBackdrop, ModalMotionSurface } from '@/components/ui/ModalMotion';

type DeleteAccountModalProps = { visible: boolean; isPasswordRequired: boolean; deleting: boolean; error: string; onClose: () => void; onDelete: (password: string) => void };
export default function DeleteAccountModal({ visible, isPasswordRequired, deleting, error, onClose, onDelete }: DeleteAccountModalProps) {
  const { colors } = useAppTheme();
  const styles = useMemo(() => createStyles(colors), [colors]);
  const [password, setPassword] = useState(''); const [confirmed, setConfirmed] = useState(false);
  const handleClose = () => { if (deleting) return; setPassword(''); setConfirmed(false); onClose(); };
  return <Modal visible={visible} transparent animationType="none" statusBarTranslucent navigationBarTranslucent presentationStyle="overFullScreen" onRequestClose={handleClose}><ModalBackdrop onPress={handleClose} style={styles.backdrop}><ModalMotionSurface variant="dialog" style={styles.card}><Pressable onPress={(event) => event.stopPropagation()}>
    <AnimatedActionButton onPress={handleClose} style={styles.close} accessibilityLabel="Close account deletion"><X size={20} color={colors.icon} /></AnimatedActionButton><View style={styles.icon}><AlertTriangle size={30} color={colors.destructive} /></View>
    <Text style={styles.title}>Permanently delete account?</Text><Text style={styles.message}>This removes your credentials, profile, content, messages, relationships, memberships, activity, and active cloud files. This cannot be undone.</Text>
    {isPasswordRequired ? <TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Current password" placeholderTextColor={colors.mutedText} style={styles.input} /> : null}
    <AnimatedActionButton disabled={deleting} onPress={() => setConfirmed((current) => !current)} style={styles.confirmRow} feedback="warning" pressScale={0.97} playful={false} accessibilityLabel="Confirm permanent deletion"><View style={[styles.checkbox, confirmed && styles.checkboxChecked]}>{confirmed ? <Check size={14} color="#ffffff" /> : null}</View><Text style={styles.confirmText}>I understand this deletion is permanent.</Text></AnimatedActionButton>
    {error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}
    <View style={styles.actions}><AnimatedActionButton disabled={deleting} onPress={handleClose} style={styles.cancel} accessibilityLabel="Cancel account deletion"><Text style={styles.cancelText}>Cancel</Text></AnimatedActionButton><AnimatedActionButton disabled={deleting || !confirmed || (isPasswordRequired && !password)} onPress={() => onDelete(password)} feedback="warning" accessibilityLabel="Delete account forever" style={[styles.deleteButton, (!confirmed || deleting || (isPasswordRequired && !password)) && styles.disabled]}>{deleting ? <ActivityIndicator color="#ffffff" /> : <Text style={styles.deleteText}>Delete forever</Text>}</AnimatedActionButton></View>
  </Pressable></ModalMotionSurface></ModalBackdrop></Modal>;
}
type ThemeColors = ReturnType<typeof useAppTheme>['colors'];

const createStyles = (colors: ThemeColors) => StyleSheet.create({ backdrop: { flex: 1, backgroundColor: colors.modalScrim, justifyContent: 'center', padding: 22 }, card: { backgroundColor: colors.surface, borderRadius: 22, padding: 22 }, close: { alignSelf: 'flex-end' }, icon: { alignSelf: 'center', width: 58, height: 58, borderRadius: 29, backgroundColor: colors.destructiveSurface, alignItems: 'center', justifyContent: 'center', marginBottom: 12 }, title: { color: colors.text, fontSize: 20, fontWeight: '900', textAlign: 'center' }, message: { color: colors.mutedText, textAlign: 'center', lineHeight: 20, marginTop: 8, marginBottom: 16 }, input: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.input, borderRadius: 12, paddingHorizontal: 13, paddingVertical: 11, color: colors.text }, confirmRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 14 }, checkbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, checkboxChecked: { backgroundColor: colors.destructive, borderColor: colors.destructive }, confirmText: { flex: 1, color: colors.secondaryText, fontSize: 13, fontWeight: '700' }, error: { color: colors.destructiveText, backgroundColor: colors.destructiveSurface, borderRadius: 10, padding: 10, marginTop: 12 }, actions: { flexDirection: 'row', gap: 10, marginTop: 18 }, cancel: { flex: 1, minHeight: 45, borderRadius: 12, backgroundColor: colors.control, alignItems: 'center', justifyContent: 'center' }, cancelText: { color: colors.secondaryText, fontWeight: '800' }, deleteButton: { flex: 1, minHeight: 45, borderRadius: 12, backgroundColor: colors.destructive, alignItems: 'center', justifyContent: 'center' }, deleteText: { color: '#ffffff', fontWeight: '900' }, disabled: { opacity: 0.45 } });
